<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $citiesByState = [
            "Andhra Pradesh" => [
                "Visakhapatnam",
                "Vijayawada",
                "Guntur",
                "Nellore",
                "Kurnool",
                "Rajahmundry",
                "Kakinada",
                "Tirupati",
                "Anantapur",
                "Kadapa",
                "Ongole",
                "Eluru",
                "Chittoor",
                "Tenali",
                "Proddatur",
                "Nandyal",
                "Machilipatnam",
                "Hindupur",
                "Srikakulam",
                "Vizianagaram"
            ],
            "Arunachal Pradesh" => [
                "Itanagar",
                "Naharlagun",
                "Pasighat",
                "Tawang",
                "Ziro",
                "Roing",
                "Bomdila",
                "Tezu",
                "Seppa",
                "Along",
                "Namsai",
                "Yingkiong",
                "khonsa",
                "Changlang"
            ],
            "Assam" => [
                "Guwahati",
                "Silchar",
                "Dibrugarh",
                "Jorhat",
                "Tinsukia",
                "Nagaon",
                "Sivasagar",
                "Goalpara",
                "Barpeta",
                "Karimganj",
                "Diphu",
                "Bongaigaon",
                "North Lakhimpur",
                "Haflong",
                "Golaghat"
            ],
            "Bihar" => [
                "Patna",
                "Gaya",
                "Bhagalpur",
                "Muzaffarpur",
                "Darbhanga",
                "Purnia",
                "Arrah",
                "Begusarai",
                "Katihar",
                "Chhapra",
                "Bettiah",
                "Saharsa",
                "Hajipur",
                "Siwan",
                "Munger",
                "Motihari",
                "Samastipur",
                "Buxar",
                "Sitamarhi",
                "Jehanabad",
            ],
            "Chhattisgarh" => [
                "Raipur",
                "Bhilai",
                "Bilaspur",
                "Korba",
                "Durg",
                "Rajnandgaon",
                "Jagdalpur",
                "Ambikapur",
                "Raigarh",
                "Dhamtari",
                "Kanker",
                "Mahasamund",
                "Janjgir",
                "Kawardha",
            ],

            "Goa" => [
                "Panaji",
                "Margao",
                "Vasco da Gama",
                "Mapusa",
                "Ponda",
                "Curchorem",
                "Bicholim",
                "Canacona",
                "Sanquelim",
                "Quepem",
            ],

            "Gujarat" => [
                "Ahmedabad",
                "Surat",
                "Vadodara",
                "Rajkot",
                "Bhavnagar",
                "Jamnagar",
                "Junagadh",
                "Gandhinagar",
                "Anand",
                "Nadiad",
                "Morbi",
                "Bharuch",
                "Porbandar",
                "Valsad",
                "Navsari",
                "Mehsana",
                "Patan",
                "Godhra",
                "Dahod",
            ],

            "Haryana" => [
                "Gurugram",
                "Faridabad",
                "Panipat",
                "Ambala",
                "Karnal",
                "Hisar",
                "Rohtak",
                "Sonipat",
                "Panchkula",
                "Yamunanagar",
                "Sirsa",
                "Rewari",
                "Bahadurgarh",
                "Palwal",
                "Kaithal",
                "Jind",
                "Bhiwani",
                "Kurukshetra",
            ],

            "Himachal Pradesh" => [
                "Shimla",
                "Dharamshala",
                "Mandi",
                "Solan",
                "Palampur",
                "Hamirpur",
                "Bilaspur",
                "Chamba",
                "Kullu",
                "Manali",
                "Una",
                "Nahan",
                "Kangra",
                "Keylong",
                "Reckong Peo",
            ],

            "Jharkhand" => [
                "Ranchi",
                "Jamshedpur",
                "Dhanbad",
                "Bokaro Steel City",
                "Hazaribagh",
                "Deoghar",
                "Giridih",
                "Ramgarh",
                "Chakradharpur",
                "Phusro",
                "Medininagar (Daltonganj)",
                "Chaibasa",
                "Godda",
                "Jhumri Telaiya",
                "Sahibganj",
                "Lohardaga",
                "Pakur",
                "Simdega",
            ],

            "Karnataka" => [
                "Bengaluru",
                "Mysuru",
                "Mangaluru",
                "Hubballi",
                "Dharwad",
                "Belagavi",
                "Kalaburagi",
                "Ballari",
                "Davangere",
                "Shivamogga",
                "Tumakuru",
                "Raichur",
                "Bidar",
                "Udupi",
                "Kolar",
                "Hassan",
                "Chitradurga",
                "Chikkamagaluru",
                "Bagalkot",
                "Mandya",
            ],

            "Kerala" => [
                "Thiruvananthapuram",
                "Kochi",
                "Kozhikode",
                "Kollam",
                "Thrissur",
                "Alappuzha",
                "Palakkad",
                "Kottayam",
                "Kannur",
                "Malappuram",
                "Pathanamthitta",
                "Idukki",
                "Kasargod",
                "Muvattupuzha",
                "Chengannur",
            ],

            "Madhya Pradesh" => [
                "Bhopal",
                "Indore",
                "Gwalior",
                "Jabalpur",
                "Ujjain",
                "Sagar",
                "Dewas",
                "Satna",
                "Ratlam",
                "Khandwa",
                "Rewa",
                "Chhindwara",
                "Shivpuri",
                "Murwara (Katni)",
                "Sehore",
                "Hoshangabad",
                "Mandsaur",
                "Seoni",
                "Vidisha",
                "Betul",
            ],

            "Maharashtra" => [
                "Mumbai",
                "Pune",
                "Nagpur",
                "Nashik",
                "Aurangabad",
                "Solapur",
                "Amravati",
                "Kolhapur",
                "Sangli",
                "Satara",
                "Akola",
                "Chandrapur",
                "Jalgaon",
                "Latur",
                "Dhule",
                "Ahmednagar",
                "Parbhani",
                "Wardha",
                "Beed",
                "Ratnagiri",
            ],

            "Manipur" => [
                "Imphal",
                "Thoubal",
                "Kakching",
                "Churachandpur",
                "Ukhrul",
                "Senapati",
                "Bishnupur",
                "Jiribam",
                "Tamenglong",
                "Moreh",
            ],

            "Meghalaya" => [
                "Shillong",
                "Tura",
                "Jowai",
                "Nongstoin",
                "Baghmara",
                "Williamnagar",
                "Resubelpara",
                "Mairang",
                "Mawkyrwat",
                "Khliehriat",
            ],

            "Mizoram" => [
                "Aizawl",
                "Lunglei",
                "Saiha",
                "Champhai",
                "Serchhip",
                "Kolasib",
                "Mamit",
                "Lawngtlai",
                "Hnahthial",
                "Saitual",
            ],

            "Nagaland" => [
                "Kohima",
                "Dimapur",
                "Mokokchung",
                "Tuensang",
                "Wokha",
                "Zunheboto",
                "Mon",
                "Phek",
                "Kiphire",
                "Longleng",
                "Peren",
            ],

            "Odisha" => [
                "Bhubaneswar",
                "Cuttack",
                "Rourkela",
                "Berhampur",
                "Sambalpur",
                "Puri",
                "Balasore",
                "Bhadrak",
                "Baripada",
                "Jharsuguda",
                "Angul",
                "Jeypore",
                "Kendrapara",
                "Rayagada",
                "Paradip",
                "Khurda",
                "Phulbani",
            ],

            "Punjab" => [
                "Amritsar",
                "Ludhiana",
                "Jalandhar",
                "Patiala",
                "Bathinda",
                "Mohali",
                "Hoshiarpur",
                "Moga",
                "Pathankot",
                "Firozpur",
                "Sangrur",
                "Kapurthala",
                "Barnala",
                "Fazilka",
                "Rupnagar",
                "Malerkotla",
                "Muktsar",
            ],

            "Rajasthan" => [
                "Jaipur",
                "Jodhpur",
                "Udaipur",
                "Kota",
                "Ajmer",
                "Bikaner",
                "Alwar",
                "Bhilwara",
                "Sikar",
                "Pali",
                "Tonk",
                "Chittorgarh",
                "Nagaur",
                "Barmer",
                "Jaisalmer",
                "Hanumangarh",
                "Sri Ganganagar",
                "Dholpur",
                "Bundi",
                "Jhunjhunu",
            ],

            "Sikkim" => [
                "Gangtok",
                "Namchi",
                "Gyalshing",
                "Mangan",
                "Rangpo",
                "Singtam",
                "Jorethang",
                "Pelling",
                "Soreng",
                "Chungthang",
            ],

            "Tamil Nadu" => [
                "Ariyalur",
                "Chengalpattu",
                "Chennai",
                "Coimbatore",
                "Cuddalore",
                "Dharmapuri",
                "Dindigul",
                "Erode",
                "Kallakurichi",
                "Kanchipuram",
                "Kanyakumari (Nagercoil)",
                "Karur",
                "Krishnagiri",
                "Madurai",
                "Nagapattinam",
                "Namakkal",
                "Nilgiris (Ooty)",
                "Perambalur",
                "Pudukkottai",
                "Ramanathapuram",
                "Ranipet",
                "Salem",
                "Sivagangai",
                "Tenkasi",
                "Thanjavur",
                "Theni",
                "Thoothukudi",
                "Tiruchirappalli",
                "Tirunelveli",
                "Tirupattur",
                "Tiruppur",
                "Tiruvallur",
                "Tiruvannamalai",
                "Tiruvarur",
                "Vellore",
                "Viluppuram",
                "Virudhunagar",
                "Mayiladuthurai",
            ],

            "Telangana" => [
                "Adilabad",
                "Bhadradri Kothagudem",
                "Hyderabad",
                "Jagtial",
                "Jangaon",
                "Jayashankar Bhupalpally",
                "Jogulamba Gadwal",
                "Kamareddy",
                "Karimnagar",
                "Khammam",
                "Komaram Bheem Asifabad",
                "Mahabubabad",
                "Mahabubnagar",
                "Mancherial",
                "Medak",
                "Medchal–Malkajgiri",
                "Mulugu",
                "Nagarkurnool",
                "Nalgonda",
                "Narayanpet",
                "Nirmal",
                "Nizamabad",
                "Peddapalli",
                "Rajanna Sircilla",
                "Rangareddy",
                "Sangareddy",
                "Siddipet",
                "Suryapet",
                "Vikarabad",
                "Wanaparthy",
                "Warangal",
                "Hanamkonda",
                "Yadadri Bhuvanagiri",
            ],

            "Tripura" => ["Agartala", "Belonia", "Dharmanagar", "Kailashahar", "Ambassa", "Khowai", "Bishalgarh", "Udaipur"],
            "Uttar Pradesh" => [
                "Agra",
                "Aligarh",
                "Ambedkar Nagar",
                "Amethi",
                "Amroha",
                "Auraiya",
                "Ayodhya",
                "Azamgarh",
                "Baghpat",
                "Bahraich",
                "Ballia",
                "Balrampur",
                "Banda",
                "Barabanki",
                "Bareilly",
                "Basti",
                "Bhadohi",
                "Bijnor",
                "Budaun",
                "Bulandshahr",
                "Chandauli",
                "Chitrakoot",
                "Deoria",
                "Etah",
                "Etawah",
                "Farrukhabad",
                "Fatehpur",
                "Firozabad",
                "Gautam Buddha Nagar",
                "Ghaziabad",
                "Ghazipur",
                "Gonda",
                "Gorakhpur",
                "Hamirpur",
                "Hapur",
                "Hardoi",
                "Hathras",
                "Jalaun",
                "Jaunpur",
                "Jhansi",
                "Kannauj",
                "Kanpur Dehat",
                "Kanpur Nagar",
                "Kasganj",
                "Kaushambi",
                "Kushinagar",
                "Lakhimpur Kheri",
                "Lalitpur",
                "Lucknow",
                "Maharajganj",
                "Mahoba",
                "Mainpuri",
                "Mathura",
                "Mau",
                "Meerut",
                "Mirzapur",
                "Moradabad",
                "Muzaffarnagar",
                "Pilibhit",
                "Pratapgarh",
                "Prayagraj",
                "Rae Bareli",
                "Rampur",
                "Saharanpur",
                "Sambhal",
                "Sant Kabir Nagar",
                "Shahjahanpur",
                "Shamli",
                "Shravasti",
                "Siddharthnagar",
                "Sitapur",
                "Sonbhadra",
                "Sultanpur",
                "Unnao",
                "Varanasi",
            ],

            "Uttarakhand" => [
                "Almora",
                "Bageshwar",
                "Chamoli",
                "Champawat",
                "Dehradun",
                "Haridwar",
                "Nainital",
                "Pauri Garhwal",
                "Pithoragarh",
                "Rudraprayag",
                "Tehri Garhwal",
                "Udham Singh Nagar",
                "Uttarkashi",
            ],

            "West Bengal" => [
                "Alipurduar",
                "Bankura",
                "Birbhum",
                "Cooch Behar",
                "Dakshin Dinajpur",
                "Darjeeling",
                "Hooghly",
                "Howrah",
                "Jalpaiguri",
                "Jhargram",
                "Kalimpong",
                "Kolkata",
                "Malda",
                "Murshidabad",
                "Nadia",
                "North 24 Parganas",
                "Paschim Bardhaman",
                "Paschim Medinipur",
                "Purba Bardhaman",
                "Purba Medinipur",
                "Purulia",
                "South 24 Parganas",
                "Uttar Dinajpur",
            ],

            "Andaman and Nicobar Islands" => [
                "Port Blair",
                "Garacharma",
                "Bambooflat",
                "Prothrapur",
                "Rangat",
                "Mayabunder",
                "Diglipur",
                "Hut Bay",
                "Car Nicobar",
                "Campbell Bay",
            ],

            "Chandigar" => [
                "Chandigarh",
                "Mani Majra",
            ],

            "Delhi" => [
                "Central Delhi",
                "East Delhi",
                "New Delhi",
                "North Delhi",
                "North East Delhi",
                "North West Delhi",
                "Shahdara",
                "South Delhi",
                "South East Delhi",
                "South West Delhi",
                "West Delhi",
            ],

            "Jammu and Kashmir" => [
                "Jammu",
                "Srinagar",
                "Anantnag",
                "Baramulla",
                "Budgam",
                "Bandipora",
                "Doda",
                "Ganderbal",
                "Kathua",
                "Kishtwar",
                "Kulgam",
                "Kupwara",
                "Poonch",
                "Pulwama",
                "Rajouri",
                "Ramban",
                "Reasi",
                "Samba",
                "Shopian",
                "Udhampur",
            ],

            "Ladakh" => [
                "Leh",
                "Kargil",
            ],

            "Lakshadweep" => [
                "Kavaratti",
                "Agatti",
                "Amini",
                "Andrott",
                "Bitra",
                "Chetlat",
                "Kadmat",
                "Kalpeni",
                "Kiltan",
                "Minicoy",
            ],

            "Puducherry" => [
                "Puducherry",
                "Karaikal",
                "Mahe",
                "Yanam",
            ],

        ];

        foreach ($citiesByState as $stateName => $cities) {
            $state = DB::table('state')->where('state_name', $stateName)->first();

            if ($state) {
                foreach ($cities as $city) {
                    DB::table('cities')->insert([
                        'state_id'   => $state->id,
                        'city_name'  => $city,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                }
            }
        }
    }
}
